### ISSUE TITLE
[Request] Order Complete

### ISSUE THREAD

**Issue by Veldkornet** [MikeBrink/home-assistant-picnic#2]
I recall, from using the Homey app, that I could it was possible to get your last purchase with the amount of euro.

I notice that there is a "cart" which is updated with this information, but once you actually purchase the items, that's reset to 0.
Hence, ideally, I'd like to see the same but for the order that was just completed.

Would this be possible?

**Comment by MikeBrink** [comment]
Hi,

This is possible. How would you like the implementation? There are a few options:

- Only see the previous order, or n previous orders? (where n would be a config option)
- add a new sensor or add the information in an existing sensor?

Would love to hear your ideas on this!

**Comment by Veldkornet** [comment]
Hmm, so this is how I plan to use it for some pretty basic notifications to begin with, maybe this gives some ideas, maybe a lot of it would overlap with #3 

Basically, whenever an order is placed, I'd create a notification to say that n items were ordered for X euro, and the delivery date is planned for between xxx and xxx.
Then another notification if the timeframes are updated.
Then lastly, that the order has been delivered.

So I guess I would have it added to the picnic_delivery sensor, since it all has to do with the current delivery. That way it shows everything about the "current" order (Items, amount, Delivery timeframe, current status???). I don't know if they actually give a status (pending / ordered / on the way/ complete).

I know in the app they let you see where the delivery is even. More of a nice to have it's available and easy to put in ;-)

I suppose previous n orders may also be an addition to the above, but then I'd add that as an additional sensor which would show the last n deliveries, config dependant as you mention

**Comment by MikeBrink** [comment]
This issue is mostly implemented, I’d love to add the ability to plot the driver on the map in the future!
