### ISSUE TITLE
[Request] Delivery Status Improvements

### ISSUE THREAD

**Issue by Veldkornet** [MikeBrink/home-assistant-picnic#3]
I see there is a scheduled delivery sensor which shows the time windows etc nicely.

As an addition to this, would it be possible to have a section for if there is a delivery planned and if a delivery was successful? 
I seem to recall having these in the Homey app, and would help me setup flows a lot easier.

**Comment by MikeBrink** [comment]
Adding if there is a delivery planned can be done easily. I think that I'll implement this via the state of the delivery sensor. This will include the following states:

- Unknown (default)
- Order_placed (order is placed but manipulations (may) be possible)
- Order_announced (The order is announced (can't be manipulated))
- Successful (delivery was successful)

Does this work for you? This will mostly mirror the homey implementation

**Comment by Veldkornet** [comment]
Sure, that works for me, it's all the info I need 👍

**Comment by MikeBrink** [comment]
I've implemented some variation of the idea above in the dev branch. It seems to be that Picnic has implemented the same system in their api, but I'm not able to test that yet. My next order will somewhere around next week, so I'll be able to test it then ;)

**Comment by MikeBrink** [comment]
You can now find the updated sensor states in the new release v0.2.0!

The states are:

- order_placed
- order_announed (update to the eta mostly and the morning of delivery)
- order_delivered

Good luck! ;)
